#!/usr/bin/python

import imaplib
obj = imaplib.IMAP4_SSL('imap.gmail.com',993)
obj.login('ArrietaDavid2001@gmail.com','david_4rr13t4') # write your email and password
obj.select()
print(len(obj.search(None, 'UnSeen')[1][0].split()))
